# Generated by Django 5.0.4 on 2024-04-25 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='courses.Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
